import { schema } from "@zero-git/db";
import { drizzleZeroConfig } from "drizzle-zero";

export default drizzleZeroConfig(schema, {
	tables: {
		usersTable: {
			id: true,
			email: true,
			githubId: true,
			githubEmail: true,
			githubAvatarUrl: true,
			githubName: true,
			createdAt: true,
			modifiedAt: true,
		},
		organizationsTable: {
			id: true,
			githubId: true,
			name: true,
			displayName: true,
			avatarUrl: true,
			createdAt: true,
			modifiedAt: true,
		},
		reposTable: {
			id: true,
			githubId: true,
			orgId: true,
			name: true,
			visibility: true,
			stars: true,
			createdAt: true,
			modifiedAt: true,
		},
		treesTable: {
			sha: true,
			orgId: true,
			repoId: true,
			createdAt: true,
			modifiedAt: true,
		},
		treeNodesTable: {
			sha: true,
			orgId: true,
			repoId: true,
			path: true,
			mode: true,
			type: true,
			size: true,
			createdAt: true,
			modifiedAt: true,
		},
		nodesInTree: {
			tree_sha: true,
			node_sha: true,
			orgId: true,
			repoId: true,
			createdAt: true,
			modifiedAt: true,
		},
		pullRequestsTable: {
			id: true,
			githubId: true,
			orgId: true,
			repoId: true,
			title: true,
			number: true,
			state: true,
			locked: true,
			body: true,
			createdAt: true,
			modifiedAt: true,
		},
		githubEventsTable: {
			id: true,
			type: true,
			actorId: true,
			repoId: true,
			orgId: true,
			isPublic: true,
			content: true,
			createdAt: true,
		},
	},
});
