/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { default as DrizzleConfigSchema } from "./drizzle-zero.config";

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof DrizzleConfigSchema;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
	tables: {
		githubEventsTable: {
			name: "githubEventsTable",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				type: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				actorId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "actor_id",
				},
				repoId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "repo_id",
				},
				orgId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "org_id",
				},
				isPublic: {
					type: "boolean",
					optional: false,
					customType: null as unknown,
					serverName: "is_public",
				},
				content: {
					type: "json",
					optional: false,
					customType: null as unknown,
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
			},
			primaryKey: ["id"],
			serverName: "github_events",
		},
		nodesInTree: {
			name: "nodesInTree",
			columns: {
				tree_sha: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				node_sha: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				orgId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "org_id",
				},
				repoId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "repo_id",
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["tree_sha", "node_sha"],
			serverName: "nodes_in_tree",
		},
		organizationsTable: {
			name: "organizationsTable",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				githubId: {
					type: "number",
					optional: false,
					customType: null as unknown,
					serverName: "github_id",
				},
				name: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				displayName: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "diaplay_name",
				},
				avatarUrl: {
					type: "string",
					optional: true,
					customType: null as unknown,
					serverName: "avatar_url",
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["id"],
			serverName: "organizations",
		},
		pullRequestsTable: {
			name: "pullRequestsTable",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				githubId: {
					type: "number",
					optional: false,
					customType: null as unknown,
					serverName: "github_id",
				},
				orgId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "org_id",
				},
				repoId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "repo_id",
				},
				title: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "name",
				},
				number: {
					type: "number",
					optional: false,
					customType: null as unknown,
				},
				state: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				locked: {
					type: "boolean",
					optional: true,
					customType: null as unknown,
				},
				body: {
					type: "string",
					optional: true,
					customType: null as unknown,
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["id"],
			serverName: "pull_requests",
		},
		reposTable: {
			name: "reposTable",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				githubId: {
					type: "number",
					optional: false,
					customType: null as unknown,
					serverName: "github_id",
				},
				orgId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "org_id",
				},
				name: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				visibility: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				stars: {
					type: "number",
					optional: true,
					customType: null as unknown,
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["id"],
			serverName: "repos",
		},
		treeNodesTable: {
			name: "treeNodesTable",
			columns: {
				sha: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				orgId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "org_id",
				},
				repoId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "repo_id",
				},
				path: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				mode: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				type: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				size: {
					type: "number",
					optional: false,
					customType: null as unknown,
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["sha"],
			serverName: "tree_nodes",
		},
		treesTable: {
			name: "treesTable",
			columns: {
				sha: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				orgId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "org_id",
				},
				repoId: {
					type: "string",
					optional: false,
					customType: null as unknown,
					serverName: "repo_id",
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["sha"],
			serverName: "trees",
		},
		usersTable: {
			name: "usersTable",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				email: {
					type: "string",
					optional: false,
					customType: null as unknown,
				},
				githubId: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "github_id",
				},
				githubEmail: {
					type: "string",
					optional: true,
					customType: null as unknown,
					serverName: "github_email",
				},
				githubAvatarUrl: {
					type: "string",
					optional: true,
					customType: null as unknown,
					serverName: "github_avatar_url",
				},
				githubName: {
					type: "string",
					optional: true,
					customType: null as unknown,
					serverName: "github_name",
				},
				createdAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "created_at",
				},
				modifiedAt: {
					type: "number",
					optional: true,
					customType: null as unknown,
					serverName: "modified_at",
				},
			},
			primaryKey: ["id"],
			serverName: "users",
		},
	},
	relationships: {
		githubEventsTable: {
			actor: [
				{
					sourceField: ["actorId"],
					destField: ["id"],
					destSchema: "usersTable",
					cardinality: "one",
				},
			],
			org: [
				{
					sourceField: ["orgId"],
					destField: ["id"],
					destSchema: "organizationsTable",
					cardinality: "one",
				},
			],
			repo: [
				{
					sourceField: ["repoId"],
					destField: ["id"],
					destSchema: "reposTable",
					cardinality: "one",
				},
			],
		},
		nodesInTree: {
			tree: [
				{
					sourceField: ["tree_sha"],
					destField: ["sha"],
					destSchema: "treesTable",
					cardinality: "one",
				},
			],
			node: [
				{
					sourceField: ["node_sha"],
					destField: ["sha"],
					destSchema: "treeNodesTable",
					cardinality: "one",
				},
			],
			org: [
				{
					sourceField: ["orgId"],
					destField: ["id"],
					destSchema: "organizationsTable",
					cardinality: "one",
				},
			],
			repo: [
				{
					sourceField: ["repoId"],
					destField: ["id"],
					destSchema: "reposTable",
					cardinality: "one",
				},
			],
		},
		organizationsTable: {
			repos: [
				{
					sourceField: ["id"],
					destField: ["orgId"],
					destSchema: "reposTable",
					cardinality: "many",
				},
			],
		},
		pullRequestsTable: {
			org: [
				{
					sourceField: ["orgId"],
					destField: ["id"],
					destSchema: "organizationsTable",
					cardinality: "one",
				},
			],
			repo: [
				{
					sourceField: ["repoId"],
					destField: ["id"],
					destSchema: "reposTable",
					cardinality: "one",
				},
			],
		},
		reposTable: {
			org: [
				{
					sourceField: ["orgId"],
					destField: ["id"],
					destSchema: "organizationsTable",
					cardinality: "one",
				},
			],
		},
		treeNodesTable: {
			nodesInTree: [
				{
					sourceField: ["sha"],
					destField: ["node_sha"],
					destSchema: "nodesInTree",
					cardinality: "many",
				},
			],
			org: [
				{
					sourceField: ["orgId"],
					destField: ["id"],
					destSchema: "organizationsTable",
					cardinality: "one",
				},
			],
			repo: [
				{
					sourceField: ["repoId"],
					destField: ["id"],
					destSchema: "reposTable",
					cardinality: "one",
				},
			],
		},
		treesTable: {
			nodesInTree: [
				{
					sourceField: ["sha"],
					destField: ["tree_sha"],
					destSchema: "nodesInTree",
					cardinality: "many",
				},
			],
			org: [
				{
					sourceField: ["orgId"],
					destField: ["id"],
					destSchema: "organizationsTable",
					cardinality: "one",
				},
			],
			repo: [
				{
					sourceField: ["repoId"],
					destField: ["id"],
					destSchema: "reposTable",
					cardinality: "one",
				},
			],
		},
	},
} as Schema;
