/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/AppContainer.vue')['default']
    AppMarkdown: typeof import('./src/components/AppMarkdown.vue')['default']
    Col: typeof import('./src/components/Col.vue')['default']
    ColorModeButton: typeof import('./src/components/ColorModeButton.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    ItemListCell: typeof import('./src/components/ItemListCell.vue')['default']
    MaybeWrap: typeof import('./src/components/MaybeWrap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/Row.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBreadcrumb: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCommandPalette: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UTable: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UTree: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.2_@babel+parser@7.27.2_aws4fetch@1.0.20_embla-carousel@8.6.0_typescript@5._6a1293d1be0acfb39a04032b21923ce3/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
  }
}
